name: CMake

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

env:
  BUILD_TYPE: Release

jobs:
  build-linux:
    runs-on: "ubuntu-22.04"

    steps:
      - uses: "actions/checkout@v3"
      
      - name: "Install ninja-build tool"
        uses: "seanmiddleditch/gha-setup-ninja@v3"

      - name: "Configure CMake"
        run: "cmake -B ${{github.workspace}}/build -G Ninja -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}"

      - name: "Build"
        run: "cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}"

      - name: "Test"
        working-directory: "${{github.workspace}}/build"
        run: "ctest -C ${{env.BUILD_TYPE}}"

  build-macos-x86_64:
    runs-on: "macos-12"

    steps:
      - uses: "actions/checkout@v3"
      
      - name: "Install ninja-build tool"
        uses: "seanmiddleditch/gha-setup-ninja@v3"

      - name: "Configure CMake"
        run: |
          cmake -B ${{github.workspace}}/build -G Ninja -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
            -DCMAKE_OSX_ARCHITECTURES="x86_64"

      - name: "Build"
        run: "cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}"

      - name: "Test"
        working-directory: "${{github.workspace}}/build"
        run: "ctest -C ${{env.BUILD_TYPE}}"

  build-macos-arm64:
    runs-on: "macos-12"

    steps:
      - uses: "actions/checkout@v3"
      
      - name: "Install ninja-build tool"
        uses: "seanmiddleditch/gha-setup-ninja@v3"

      - name: "Configure CMake"
        run: |
          cmake -B ${{github.workspace}}/build -G Ninja -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
            -DCMAKE_OSX_ARCHITECTURES="arm64"

      - name: "Build"
        run: "cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}"

      - name: "Test"
        working-directory: "${{github.workspace}}/build"
        run: "ctest -C ${{env.BUILD_TYPE}}"

  build-windows-x64:
    runs-on: "windows-latest"

    steps:
      - uses: "actions/checkout@v3"

      - name: "Configure CMake"
        run: |
          cmake -B ${{github.workspace}}/build -G "Visual Studio 17 2022" `
            -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} `
            -DCMAKE_GENERATOR_PLATFORM=x64

      - name: "Build"
        run: "cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}"

      - name: "Test"
        working-directory: "${{github.workspace}}/build"
        run: "ctest -C ${{env.BUILD_TYPE}}"
